import { Injectable, Logger } from '@nestjs/common';
import { AiService } from '../ai.service';

@Injectable()
export class MockAiService implements AiService {
  private readonly logger = new Logger(MockAiService.name);

  async generateContent(subject: string, keywords?: string, platform?: string): Promise<string> {
    this.logger.log(`[MOCK] Generating content for subject: "${subject}"${keywords ? ` | Keywords: ${keywords}` : ''}${platform ? ` | Platform: ${platform}` : ''}`);

    // Simulate realistic AI generation delay (3 seconds)
    await new Promise((resolve) => setTimeout(resolve, 3000));

    const keywordsSection = keywords?.trim()
      ? `\n\n**Keywords covered:** ${keywords}`
      : '';

    // Return realistic generated sample content
    const mockContent = `
# Mock Educational Content: ${subject}

This is a simulated response generated by the MockAiService.
It mimics the behavior of a real AI provider to allow local development and testing
without requiring a paid API key or hitting rate limits.

## Introduction
This article explores the topic of **${subject}** in depth.

## Key Concepts
- Fast and reliable testing.
- No network dependency.
- Easy to switch to production OpenAI later.
- Architecture decoupled via the \`AiService\` abstraction.

## Conclusion
When you switch \`USE_MOCK_AI=false\` in your \`.env\`, the real OpenAI GPT-4o-mini will
generate this content using your keywords and subject.${keywordsSection}
    `.trim();

    return mockContent;
  }
}
