import { Injectable, Logger } from '@nestjs/common';
import { AiService } from '../ai.service';

@Injectable()
export class MockAiService implements AiService {
  private readonly logger = new Logger(MockAiService.name);

  async generateContent(subject: string): Promise<string> {
    this.logger.log(`[MOCK] Generating content for subject: ${subject}`);
    
    // Simulate realistic AI generation delay (3 seconds)
    await new Promise((resolve) => setTimeout(resolve, 3000));
    
    // Return realistic generated sample content
    const mockContent = `
# Mock Educational Content: ${subject}

This is a simulated response generated by the MockAiService.
It mimics the behavior of a real AI provider to allow local development and testing
without requiring a paid API key or hitting rate limits.

**Key Concepts:**
- Fast and reliable testing.
- No network dependency.
- Easy to switch to production OpenAI later.
    `.trim();

    return mockContent;
  }
}
